dataset:
  name: tin
  num_classes: 200
  image_size: 64
  pre_size: 64

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: /data/images_classic/
    imglist_pth: /data/benchmark_imglist/tin/train_tin.txt
    batch_size: 128
    shuffle: True
    samples_per_class: -1
  val:
    dataset_class: ImglistDataset
    data_dir: /data/images_classic/
    imglist_pth: /data/benchmark_imglist/tin/val_tin.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: /data/images_classic/
    imglist_pth: /data/benchmark_imglist/tin/val_tin.txt
    batch_size: 200
    shuffle: False
