name: openood
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.8.1
  - torchvision=0.9.1
  - cudatoolkit=10.1
  - scikit-learn=0.24.2
  - json5=0.9.6
  - matplotlib=3.3.0
  - scipy=1.5
  - tqdm=4.62.3
  - pip
  - pip:
    - pyyaml==5.4.1
    - pre-commit
    - opencv-python==4.4.0.46
    - imgaug==0.4.0
    - pandas==1.4.1
    - diffdist==0.1
    - mmcv==1.4.2
    - mmcls==0.17.0
    - Cython==0.29.30
    - faiss-gpu==1.7.2
    - gdown==4.5.1
