dataset:
  name: cifar100-c5
  num_classes: 100
  pre_size: 32
  image_size: 32

  interpolation: bilinear
  normalization_type: cifar100

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [val, test]

  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100-c5/cifar100_c5_val.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100-c5/cifar100_c5_test.txt
    batch_size: 200
    shuffle: False
