dataset:
  name: imagenet-c1
  num_classes: 1000
  pre_size: 256
  image_size: 224

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [val, test]

  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/imagenet_1k
    imglist_pth: ./data/benchmark_imglist/imagenet/val_imagenet.txt
    batch_size: 32
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet-c1/imagenet_c1_test.txt
    batch_size: 32
    shuffle: False
